# Generated by Django 5.0.2 on 2024-02-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membertype_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membertype',
            name='membertypecode',
            field=models.IntegerField(unique=True),
        ),
    ]
