# Generated by Django 5.0 on 2024-03-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adjudication',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('adjudicationcode', models.IntegerField(unique=True)),
                ('providercode', models.IntegerField()),
                ('soanumber', models.IntegerField()),
                ('soadate', models.DateField(auto_now=True)),
                ('duedate', models.DateField(auto_now=True)),
                ('claimsstatus', models.IntegerField()),
                ('remarks', models.TextField()),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField(auto_now=True)),
                ('transactype', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Adjudication',
                'indexes': [models.Index(fields=['adjudicationcode'], name='adjudicationcode_idx'), models.Index(fields=['duedate'], name='duedate_idx')],
            },
        ),
    ]
