# Generated by Django 5.0 on 2024-03-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjudication_app', '0002_alter_adjudication_claimsstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjudication',
            name='claimsstatus',
            field=models.CharField(max_length=10),
        ),
    ]
