# Generated by Django 5.0 on 2024-03-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adjudication_app', '0003_alter_adjudication_claimsstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adjudication',
            old_name='recordno',
            new_name='recordnoadju',
        ),
    ]
