# Generated by Django 5.0 on 2024-03-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjudication_app', '0004_rename_recordno_adjudication_recordnoadju'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjudication',
            name='claimsstatus',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adjudication',
            name='transactype',
            field=models.CharField(max_length=50),
        ),
    ]
