# Generated by Django 5.0 on 2024-03-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjudication_app', '0005_alter_adjudication_claimsstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjudication',
            name='duedate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='adjudication',
            name='soadate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='adjudication',
            name='transactdate',
            field=models.DateTimeField(),
        ),
    ]
