# Generated by Django 5.0 on 2024-03-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adjudication_app', '0006_alter_adjudication_duedate_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adjudication',
            table='sales',
        ),
    ]
