# Generated by Django 5.0.2 on 2024-02-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('plancode', models.IntegerField()),
                ('plantype', models.CharField(max_length=100)),
                ('productcode', models.IntegerField()),
                ('roomcode', models.IntegerField()),
                ('membertypecode', models.IntegerField()),
                ('agefrom', models.DecimalField(decimal_places=6, max_digits=18)),
                ('ageto', models.DecimalField(decimal_places=6, max_digits=18)),
                ('premiumamount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('benefitlimit', models.DecimalField(decimal_places=6, max_digits=18)),
                ('limittypecode', models.IntegerField()),
                ('withaccesstotophospital', models.IntegerField()),
                ('remarks', models.TextField(null=True)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transacttype', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Plan',
                'indexes': [models.Index(fields=['plancode'], name='plancode_idx'), models.Index(fields=['plancode', 'plantype'], name='plancode_plantype_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanHistory',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('plancode', models.IntegerField()),
                ('plantype', models.CharField(max_length=100)),
                ('productcode', models.IntegerField()),
                ('roomcode', models.IntegerField()),
                ('membertypecode', models.IntegerField()),
                ('agefrom', models.DecimalField(decimal_places=6, max_digits=18)),
                ('ageto', models.DecimalField(decimal_places=6, max_digits=18)),
                ('premiumamount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('benefitlimit', models.DecimalField(decimal_places=6, max_digits=18)),
                ('limittypecode', models.IntegerField()),
                ('withaccesstotophospital', models.IntegerField()),
                ('remarks', models.TextField(null=True)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transacttype', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'PlanHistory',
                'indexes': [models.Index(fields=['recordno'], name='planrecordnoh_idx'), models.Index(fields=['plancode'], name='plancodeh_idx'), models.Index(fields=['plancode', 'plantype'], name='plancode_plantypeh_idx')],
            },
        ),
    ]
