# Generated by Django 5.0.2 on 2024-02-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0002_alter_plan_limittypecode_alter_plan_membertypecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plancode',
            field=models.IntegerField(unique=True),
        ),
    ]
