# Generated by Django 5.0.2 on 2024-02-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsHistory',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('productcode', models.IntegerField()),
                ('productname', models.CharField(max_length=255)),
                ('productshortname', models.CharField(max_length=10, null=True)),
                ('productdescription', models.CharField(max_length=255)),
                ('remarks', models.TextField(null=True)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transacttype', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ProductsHistory',
                'indexes': [models.Index(fields=['recordno'], name='recordnoh_idx'), models.Index(fields=['productcode'], name='productcodeh_idx'), models.Index(fields=['productcode', 'productname'], name='productcodeh_productnmh_idx')],
            },
        ),
    ]
