# Generated by Django 5.0.2 on 2024-02-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_productshistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productshistory',
            new_name='productrecordnoh_idx',
            old_name='recordnoh_idx',
        ),
    ]
