# Generated by Django 5.0.2 on 2024-02-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_rename_recordnoh_idx_productrecordnoh_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productcode',
            field=models.IntegerField(unique=True),
        ),
    ]
