# Generated by Django 5.0 on 2024-03-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limittype_app', '0002_alter_limittype_limittypecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('recordnoclaim', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Claims',
            },
        ),
    ]
