# Generated by Django 5.0 on 2024-03-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('limittype_app', '0003_claims'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Claims',
        ),
    ]
