# Generated by Django 5.0.2 on 2024-02-27 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomtype_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='roomtypehistory',
            new_name='roomcodeh_roomnmh_idx',
            old_name='roomcodeh_roonmh_idx',
        ),
    ]
