# Generated by Django 5.0.2 on 2024-02-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomtype_app', '0002_rename_roomcodeh_roonmh_idx_roomcodeh_roomnmh_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='roomcode',
            field=models.IntegerField(unique=True),
        ),
    ]
