# Generated by Django 5.0.2 on 2024-02-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('providercode', models.IntegerField()),
                ('categorycode', models.IntegerField()),
                ('providername', models.CharField(max_length=255)),
                ('tin', models.CharField(default='', max_length=20)),
                ('address', models.CharField(max_length=255, null=True)),
                ('emailaddress', models.EmailField(max_length=50, null=True)),
                ('locationcode', models.IntegerField()),
                ('contactperson', models.CharField(max_length=255, null=True)),
                ('landline', models.CharField(max_length=150, null=True)),
                ('mobilenumber', models.CharField(max_length=150, null=True)),
                ('remarks', models.TextField(null=True)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transacttype', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Providers',
            },
        ),
    ]
