# Generated by Django 5.0.2 on 2024-02-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='providers',
            index=models.Index(fields=['providercode'], name='providercode_idx'),
        ),
        migrations.AddIndex(
            model_name='providers',
            index=models.Index(fields=['providercode', 'providername'], name='prvdrcode_prvdrnm_idx'),
        ),
    ]
