# Generated by Django 5.0.2 on 2024-02-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0002_providers_providercode_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='providercode',
            field=models.IntegerField(unique=True),
        ),
    ]
